# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-10 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_extd',
            name='city',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='user_extd',
            name='country',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='user_extd',
            name='gender',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Mademoiselle'), (2, 'Madame'), (3, 'Monsieur')], null=True),
        ),
        migrations.AlterField(
            model_name='user_extd',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
